name: swarm_based_techniques
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2018.03.07
  - certifi=2018.4.16
  - coverage=4.5.1
  - cycler=0.10.0
  - decorator=4.3.0
  - freetype=2.8
  - intel-openmp=2018.0.0
  - kiwisolver=1.0.1
#  - libcxx=4.0.1
#  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
#  - libgfortran=3.0.1
  - libpng=1.6.34
  - matplotlib=2.2.2
  - mkl=2018.0.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - ncurses=6.1
  - networkx=2.1
  - numpy=1.14.3
  - numpy-base=1.14.3
  - openssl=1.0.2o
  - pandas=0.23.0
  - patsy=0.5.0
  - pip=10.0.1
  - pyparsing=2.2.0
  - python=3.6.5
  - python-dateutil=2.7.3
  - pytz=2018.4
  - readline=7.0
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - seaborn=0.8.1
  - setuptools=39.1.0
  - six=1.11.0
  - sqlite=3.23.1
  - statsmodels=0.9.0
  - tk=8.6.7
  - tornado=5.0.2
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11

